### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mfalt** [jverzani/GtkInteract.jl#10]
Is this package still being developed?
It doesn't seem to work for me on Fedora 22 with julia 0.4.5. I simply get either a completely black or completely transparent window depending on which window manager I use.

**Comment by jverzani** [comment]
Hmm, seems like the recent updates to Reactive and Interact have to be adjusted for. Thanks for reporting this.

**Comment by jverzani** [comment]
Well, maybe it is Gtk itself. This example from the README doesn't seem to work for me:

```
using Gtk
    win = @Window("New title") |> (f = @Frame("A frame"))
    hbox = @Box(:h)  # :h makes a horizontal layout, :v a vertical layout
    push!(f, hbox)
    cancel = @Button("Cancel")
    ok = @Button("OK")
    push!(hbox, cancel)
    push!(hbox, ok)
    showall(win)
```

Can you check on your setup?

**Comment by mfalt** [comment]
That example works as expected on my system if I start with
`using Gtk.ShortNames`
instead.

**Comment by jverzani** [comment]
Oops, sorry about that. Okay, if I could trouble you one more time. If you first load Reactive, does it still work?

```
using Gtk
using Reactive
using Gtk.ShortNames
win = @Window("New title") |> (f = @Frame("A frame"))
    hbox = @Box(:h)  # :h makes a horizontal layout, :v a vertical layout
    push!(f, hbox)
    cancel = @Button("Cancel")
    ok = @Button("OK")
    push!(hbox, cancel)
    push!(hbox, ok)
    showall(win)

```

Something in one of those packages prevents my Gtk from drawing the child widgets. I thinking #7 might be related.

**Comment by mfalt** [comment]
Nice observation, no it does not work if Reactive is loaded, either before of after Gtk.

**Comment by jverzani** [comment]
Thanks for checking. I believe I have an issue with Gtk.jl and will follow
up.

On Thu, Apr 14, 2016 at 8:28 AM, Mattias Fält <notifications@github.com>
wrote:

> Nice observation, no it does not work if Reactive is loaded, either before
> of after Gtk.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/GtkInteract.jl/issues/10#issuecomment-209914464>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Does a `Pkg.checkout("Reactive", "master")` help? It seems to for me.

**Comment by mfalt** [comment]
No, I still get a blank window even though I'm on master of Reactive, Interact and Gtk. At least on julia 0.4.2, I will try on 0.4.5 later.

**Comment by mfalt** [comment]
Same unsuccessful both when running Fedora 23 with julia 0.4.5 and Ubuntu 14.04 with julia 0.4.3. On master of Reactive, Interact, Gtk and GtkInteract.

**Comment by jverzani** [comment]
This was fixed here: https://github.com/JuliaLang/Reactive.jl/issues/93  Thanks for pinging me about the issue.
