### ISSUE TITLE
Usage with Immerse

### ISSUE THREAD

**Issue by mfalt** [jverzani/GtkInteract.jl#16]
I was trying to get this package to work with Immerse using the following flow, but had some problems. There may be simpler implementations of this, but I have found none that works with multiple plots and sliders/checkboxes (feel free to give me some pointers if there is). Below follows a toy example:
```julia
using GtkInteract, Immerse
k = slider(1:0.1:10)
cg1 = cairographic(width=200,height=150)
w = window(hbox(k,grow(cg1)))
Reactive.preserve(map(k) do k
    fig1 = Immerse.plot(y=(1:10).^k)
    push!(cg1, fig1)
end)
w
```
The code above doesn't work, but I was able to create a solution.
Would you consider adding the following function to the package? (I can create a pull request, but wanted to know if I'm using the package correctly first)
```julia
function Base.push!(obj::CairoGraphic, p::Gadfly.Plot)
    if obj.obj != nothing
      push!(obj.obj, p)
    end
end
```
The problem that the old image doesn't disappear is still present. This can be easily solved by adding a backgound to the plot:
```julia
fig1 = Immerse.plot(y=(1:10).^k, Theme(background_color=Colors.RGB(1.,1.,1.)))
```
is there a way to generalize this or solve it in some other way?

**Comment by jverzani** [comment]
I added that method. I had originally envisioned using Immerse only through `Plots` and hadn't updated. Thanks for the question!

As for the background image, I have a note in the file 

```
## XXX This has issues, as the canvas doen't get refreshed between draws
```

I couldn't figure this out when I was writing it, and haven't given any thought since. It would be nice to clear up in a general way. It seems that using Immerse is the best way to make graphics now with this package. Likely there is a Cairo command that could be called just before the line `push!(obj.obj, p)` in your addition.

**Comment by mfalt** [comment]
Great!
Yes I saw the comment in the code but didnt know how to solve it.
Yes, I haven't found any good way to use the package without Immerse since Plots dropped support for Immerse.
I looked through some of the source for GtkCanvas and was able to find the following fix. Its not elegant, but maybe it is enough, or it could give some clues:
```julia
function Base.push!(obj::CairoGraphic, p::Gadfly.Plot)
    if obj.obj != nothing
        push!(obj.obj, p)
        Gtk.notify_resize(
            convert(Ptr{Gtk.GObject}, C_NULL),
            convert(Ptr{Gtk.GdkRectangle}, C_NULL),
            obj.obj)
    end
end
```

**Comment by mfalt** [comment]
After looking some more, I think this might be a good solution, but haven't tested it a lot
```julia
function Base.push!(obj::CairoGraphic, p::Gadfly.Plot)
    canvas = obj.obj
    if canvas != nothing
        push!(canvas, p)
        canvas.back = Gtk.cairo_surface_for(canvas)
        canvas.backcc = Gtk.CairoContext(canvas.back)
        Gtk.draw(canvas, false)
    end
end
```
based on https://github.com/JuliaGraphics/Gtk.jl/blob/master/src/cairo.jl#L55
